#!/bin/bash
proteina=2E1Q.pdb
for arch in $proteina
do
  prot=$(echo $arch | sed 's/.pdb//g' )
  cp $prot.pdb old-p
  gmx editconf -f $prot.pdb -o $prot.gro -resnr 1 -c -bt cubic -d 1
  echo 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 | gmx pdb2gmx -f $prot.gro -o $prot.gro -p $prot.top -i $prot.itp -ff oplsaa -water tip3p -his -ss
#  sed -i "/16008 16007 16003 16009/ s/$/ \n\n[ distance_restraints ]\n; ai   aj   type   index   type'      low     up1     up2     fac\n16014  319     1       0       1      0.0     0.15    0.28    1.0\n16014  373     1       1       1      0.0     0.15    0.28    1.0\n16014  833     1       2       1      0.0     0.15    0.23    1.0\n16014  880     1       3       1      0.0     0.15    0.28    1.0\n16015  4652    1       4       1      0.0     0.15    0.28    1.0\n16015  4692    1       5       1      0.0     0.15    0.28    1.0\n16015  4889    1       6       1      0.0     0.15    0.28    1.0\n16015  5032    1       7       1      0.0     0.15    0.28    1.0/g" $prot.top
  gmx solvate -cp $prot.gro -cs spc216.gro -o $prot.gro -p $prot.top
  gmx grompp -f min.mdp -c $prot.gro -p $prot.top -o $prot.tpr -po $prot.mdp -maxwarn 1
  echo SOL | gmx genion -s $prot.tpr -o $prot.gro -p $prot.top -neutral -conc 0.154004106
  gmx_d grompp -f min.mdp -c $prot.gro -p $prot.top -o $prot-min.tpr -po $prot-min.mdp #-maxwarn 2
  gmx_d mdrun -nice 0 -v -s -deffnm $prot-min
done
rm \#*
patr="step*"
if ls ${patr} 1> /dev/null 2>&1; then
  for archivo in ${patr};
  do
    rm "$archivo"
        echo "Eliminando $archivo"
  done
else
  echo "No se encontraron archivos que coincidan con el patrón."
fi
patr="dd_dump*"
if ls ${patr} 1> /dev/null 2>&1; then
  for archivo in ${patr};
  do
      rm "$archivo"
      echo "Eliminando $archivo"
  done
else
  echo "No se encontraron archivos que coincidan con el patrón."
fi









