#!/bin/bash
proteina=2E1Q.pdb
for arch in $proteina
do
  prot=$(echo $arch | sed 's/.pdb//g' )
# gmx grompp -f npt.mdp -c $prot-nvt.gro -p $prot.top -o $prot-npt.tpr -po $prot-npt.mdp
# gmx mdrun -nice 0 -v -s -ddorder pp_pme -deffnm $prot-npt -nt 32
   gmx mdrun -nice 0 -v -s -deffnm $prot-npt -cpi $prot-npt.cpt -cpo $prot-npt-01.cpt
done
rm \#*
patr="step*"
if ls ${patr} 1> /dev/null 2>&1; then
  for archivo in ${patr};
  do
    rm "$archivo"
        echo "Eliminando $archivo"
  done
else
  echo "No se encontraron archivos que coincidan con el patrón."
fi
patr="dd_dump*"
if ls ${patr} 1> /dev/null 2>&1; then
  for archivo in ${patr};
  do
      rm "$archivo"
      echo "Eliminando $archivo"
  done
else
  echo "No se encontraron archivos que coincidan con el patrón."
fi
